# CMSC 430 Project 1 - Makefile
# Author: Mackenzie Treadway
# Date: August 26, 2025
#
# Builds the lexical analyzer project

all: lexer

lexer: lexer.o listing.o lex.yy.o
	g++ -o lexer lexer.o listing.o lex.yy.o

lexer.o: lexer.cc listing.h tokens.h
	g++ -c lexer.cc

listing.o: listing.cc listing.h
	g++ -c listing.cc

lex.yy.o: scanner.l tokens.h listing.h
	flex scanner.l
	g++ -c lex.yy.c

clean:
	rm -f *.o lexer lex.yy.c
